require 'rake/clean'

OTT_OPTIONS = "-merge true -tex_show_meta false -tex_wrap false"
OTT_FILES = "rules.ott"
OTT_RESULT_FILES = "ott-rules.tex"

calculus = "main"

file OTT_RESULT_FILES => OTT_FILES do
  sh "ott #{OTT_OPTIONS} #{OTT_FILES} -o #{OTT_RESULT_FILES}"
end

CLEAN << OTT_RESULT_FILES

clean_exts = %w[.mng .aux .pdf .brf .bbl .fls .out .log .blg .lot .toc .xdv .fdb_latexmk]

clean_exts.each { |c_ext|
  CLEAN << calculus.ext(c_ext)
}

file "#{calculus}.mng" do
  sh "ott #{OTT_OPTIONS} #{OTT_FILES} -tex_filter #{calculus}.tex #{calculus}.mng"
end

task :default => ["#{calculus}.mng", OTT_RESULT_FILES] do
  sh "latexmk -xelatex #{calculus}.mng"
end
